### ISSUE TITLE
Pages using archetypes not showing relation

### ISSUE THREAD

**Issue by John-gecko** [dawoe/umbraco-nexu#35] opened 2018-07-26 11:04 UTC
Hi

So having issues with archetypes relations
Here is a simplified set up so you can reproduce the environment
using umbraco 7.10.4
1 Add the archetype package
2 Create a data type called widgets and int the developer option paste the supplied json to create the 2 fieldsets

`{"showAdvancedOptions":false,"startWithAddButton":true,"hideFieldsetToolbar":false,"enableMultipleFieldsets":true,"hideFieldsetControls":false,"hidePropertyLabel":false,"maxFieldsets":null,"enableCollapsing":true,"enableCloning":true,"enableDisabling":true,"enableDeepDatatypeRequests":false,"fieldsets":[{"alias":"richTextEditor","remove":false,"collapse":true,"labelTemplate":"Rich Text Editor: {{label}}","icon":"icon-forms-file-powerpoint","label":"Rich Text Editor","properties":[{"alias":"label","remove":false,"collapse":true,"label":"Label","helpText":"","dataTypeGuid":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","value":"","aliasIsDirty":true},{"alias":"showLabelAsComponentHeading","remove":false,"collapse":true,"label":"Show label as component heading","helpText":"","dataTypeGuid":"90609856-619b-44ba-a456-da06e609ba5c","value":"","aliasIsDirty":true},{"alias":"richTextEditor","remove":false,"collapse":true,"label":"Rich Text Editor","helpText":"","dataTypeGuid":"ca90c950-0aff-4e72-b976-a30b1ac57dad","value":"","aliasIsDirty":true}],"group":{"name":"Content"},"aliasIsDirty":true,"$$hashKey":"1V6"},{"alias":"multiplePromos","remove":false,"collapse":true,"labelTemplate":"Promos: {{label}}","icon":"icon-thumbnails-small color-green","label":"Promos","properties":[{"alias":"label","remove":false,"collapse":true,"label":"Label","helpText":"","dataTypeGuid":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","value":"","aliasIsDirty":true},{"alias":"showLabelAsComponentHeading","remove":false,"collapse":true,"label":"Show label as component heading","helpText":"","dataTypeGuid":"90609856-619b-44ba-a456-da06e609ba5c","value":"","aliasIsDirty":true},{"alias":"promoPicker","remove":false,"collapse":true,"label":"promo picker","helpText":"","dataTypeGuid":"4e48519c-b78b-4eb4-9c1c-e3fc848f8d95","value":"","aliasIsDirty":true}],"aliasIsDirty":true,"group":{"name":"Content"},"$$hashKey":"1V7"}],"fieldsetGroups":[{"name":"Content"}],"selection":[],"hidePropertyLabels":false}`

3 on content page and add the widget data type as doctype property

4 create a structure along the following lines
 - Homepage
   -  Content Page 1 
   -  Content Page 2
     
 - Shared nodes
    -  Promos
       -  Promo 1
       -  Promo 2

5 add a promo widget to Content Page 1 and add the 2 promos
6 view the promo node (make sure is has a relation view in the doctype) 

Expected result - if the node is picked via the archetype widget then when you go to the promo node it should show a relation between it and the content page its been chosen on - right now its blank

note this is working fine for a simple content picker directly added to the content page

Please let me know if you need further details

Cheers
J

**Comment by jaandrews** [comment] 2018-07-26 17:15
Are there any errors in the trace log? I don't see any issues with the configuration. If there are no errors, you should to check that the guids in the archetype config matches up to datatypes, as the parser uses the guids to determine which parser to use for each property.

If possible, I recommend you use NestedContent instead of Archetype though. I built this parser because I had a project that used Archetype extensively, but Archetype has been [sunset](https://github.com/kgiszewski/Archetype/issues/439) because Umbraco moved the NestedContent data type into the core. At some point, Archetype will likely no longer work.

**Comment by jaandrews** [comment] 2018-07-27 16:56
Took another look at the config you sent over and it looks like you have two properties with an alias of label, which would explain the error.

As for Nested Content, it is mature. It started as a [plugin](https://our.umbraco.com/projects/backoffice-extensions/nested-content/) that was released for umbraco 7.2 and was pulled into the umbraco core in version 7.7. One of it's advantages is that it uses the same apis that umbraco uses for published content, so developers don't have to learn 2 sets of apis. The main downside is that it's a little more work to set up, as you have to create a doc type for it to connect to instead of configuring all of the settings within the data type. What feature are you using that nested content doesn't provide?

**Comment by John-gecko** [comment] 2018-07-30 08:54
Hi 
The properties with alias = "label"  (ArchetypePropertyModel)  are on different fieldsets (ArchetypeFieldsetModel)
ie each ArchetypeFieldsetModel has its own list IEnumerable<ArchetypePreValueProperty> Properties
perhaps the parser is ignoring the type when its doing its thing?

To confirm the theory re the label - I removed 1 of the fieldsets and it does indeed work with a single fieldset. - Unfortunately not much use for me as we will have about 20+ widgets/fieldsets and it would require far too much effort to refactor all the widgets
It would be like going through all the doctypes and making sure every doctype property was unique compared to other doctype properties - bit of a pain really :)

As for the nested content - don't get me wrong, I think its a great start
I gave it a go at the start of the year, but wasn't able to reproduce the functionality I had in archetypes for the content widgets I was using - sorry cannot remember which bits were missing just that I couldnt reproduce what I had for the current set of content widgets

I will have another go soon-ish, and report back
I do know we will eventually have to move over to something else - I would just like there to be as few missing bits of functionality as possible - otherwise I will get the whole "we used to be able to do that in the old version" from clients :)

Cheers
J

**Comment by dawoe** [comment] 2018-07-30 09:09
So probably something is wrong here : https://github.com/dawoe/umbraco-nexu/blob/develop/Source/Our.Umbraco.Nexu.Parsers/PropertyParsers/Community/ArchetypeParser.cs#L60

Will try to see if I find time to fix it. But I'm happy to accept a PR 😸

**Comment by John-gecko** [comment] 2018-07-30 13:07
Not sure what time I have, but when dealing with Archetypes I prefer to strong type them just so I know I am getting the right properties :)

ArchetypeModel a = node.GetPropertyValue<ArchetypeModel>("pageContent");
IEnumerable<ArchetypeFieldsetModel> fsList = a.Fieldsets;
ArchetypeFieldsetModel fs = fsList.FirstOrDefault();
IEnumerable<ArchetypePropertyModel> props = fs.Properties;
ArchetypePropertyModel prop = props.Where(x => x.Alias == propAlias).FirstOrDefault();

will see if I can get some time to look at it in the near future :)

**Comment by dawoe** [comment] 2018-08-01 15:29
Just tried to reproduce this. I have 2 properties in 2 different fieldsets with the same alias. And that works fine for me .

This is the config of my archetype : 
`{"showAdvancedOptions":false,"startWithAddButton":false,"hideFieldsetToolbar":false,"enableMultipleFieldsets":true,"hideFieldsetControls":false,"hidePropertyLabel":false,"maxFieldsets":null,"enableCollapsing":true,"enableMultipleOpen":true,"enableCloning":false,"enableDisabling":true,"enableDeepDatatypeRequests":false,"enablePublishing":false,"enableMemberGroups":false,"enableCrossDragging":false,"fieldsets":[{"alias":"fieldset1","remove":false,"collapse":true,"labelTemplate":"Article","icon":"","label":"Fieldset1","properties":[{"alias":"contentPicker","remove":false,"collapse":true,"label":"Content Picker","helpText":"","dataTypeGuid":"fd1e0da5-5606-4862-b679-5d0cf3a52a59","value":"","aliasIsDirty":true,"$$hashKey":"39I"},{"alias":"text","remove":false,"collapse":true,"label":"Text","helpText":"","dataTypeGuid":"ca90c950-0aff-4e72-b976-a30b1ac57dad","value":"","aliasIsDirty":true,"$$hashKey":"39J"}],"group":null,"aliasIsDirty":true,"$$hashKey":"396"},{"alias":"fieldset2","remove":false,"collapse":false,"labelTemplate":"Blog","icon":"","label":"Fieldset2","properties":[{"alias":"contentPicker","remove":false,"collapse":true,"label":"Content Picker","helpText":"","dataTypeGuid":"fd1e0da5-5606-4862-b679-5d0cf3a52a59","value":"","aliasIsDirty":true,"$$hashKey":"3A8"},{"alias":"image","remove":false,"collapse":true,"label":"Image","helpText":"","dataTypeGuid":"135d60e0-64d9-49ed-ab08-893c9ba44ae5","value":"","aliasIsDirty":true,"$$hashKey":"3A9"}],"group":null,"aliasIsDirty":true,"$$hashKey":"397"}],"fieldsetGroups":[]}`

This is done using the latest version of archetype

Dave

**Comment by dawoe** [comment] 2018-08-02 07:05
Hi @John-gecko and @jaandrews 

I think I fixed the parser for archetype. I was able to reproduce the issue with no all links being found by using the config of @John-gecko 

The problem was it only got the property parsesr for the first fieldset.

@John-gecko could you test it using the latest beta release ? You can find links to the nuget and umbraco package on the repository homepage

Dave

**Comment by John-gecko** [comment] 2018-08-02 10:02
Hi Dave
Will download and get back to you asap - I might not be until tomorrow though :)
Cheers
J

**Comment by dawoe** [comment] 2018-08-13 04:35
Hi @John-gecko 

Were you able to test out the latest beta version ?

dave

**Comment by John-gecko** [comment] 2018-08-13 08:56
Hi Dave
I was on leave last week and didt manage to get to this before going
I will have a look this week, once I have caught up on all my other tasks :)
And get back to you with feedback 

Cheers
J

**Comment by dawoe** [comment] 2018-08-15 06:58
Hi @John-gecko 

I tested this some more and it seems to be working now for me. This is part of the new 1.6.0 release so I will close this issue. Feel free to raise a new one when you still have problems

**Closed by dawoe** 2018-08-15 06:58 UTC
Labels: bug
